// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdSvQgE1B7bGm37xh4JronSdXe8OhOok',
    appId: '1:426330754486:web:003d5569ba724102e78517',
    messagingSenderId: '426330754486',
    projectId: 'flutter-authen-b4436',
    authDomain: 'flutter-authen-b4436.firebaseapp.com',
    storageBucket: 'flutter-authen-b4436.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFgzDLvz-8CD5B1UQP8L4znPrtJ5YnVs',
    appId: '1:426330754486:android:90a057625c2d9264e78517',
    messagingSenderId: '426330754486',
    projectId: 'flutter-authen-b4436',
    storageBucket: 'flutter-authen-b4436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpO9ABvbyUqLDYO3vku3sSocazKe7oPw',
    appId: '1:426330754486:ios:58e29b1498883da9e78517',
    messagingSenderId: '426330754486',
    projectId: 'flutter-authen-b4436',
    storageBucket: 'flutter-authen-b4436.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzpO9ABvbyUqLDYO3vku3sSocazKe7oPw',
    appId: '1:426330754486:ios:58e29b1498883da9e78517',
    messagingSenderId: '426330754486',
    projectId: 'flutter-authen-b4436',
    storageBucket: 'flutter-authen-b4436.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwdSvQgE1B7bGm37xh4JronSdXe8OhOok',
    appId: '1:426330754486:web:f554f3d494659c12e78517',
    messagingSenderId: '426330754486',
    projectId: 'flutter-authen-b4436',
    authDomain: 'flutter-authen-b4436.firebaseapp.com',
    storageBucket: 'flutter-authen-b4436.firebasestorage.app',
  );
}
